# Generated by Django 4.0.4 on 2022-05-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='artist',
            new_name='artista',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='title',
            new_name='titulo',
        ),
    ]
